### ISSUE TITLE
Actual "network-of-mirrors" TODO

### ISSUE THREAD

**Issue by wolfv** [mamba-org/quetz#241]
There are a couple of missing bits and pieces for proper network-of-mirrors:

### quetz

- [] share download count and other stats back to main instance
- [] mirroring without reindexing: reindexing is wasteful and CPU intensive, so maybe we can just copy from repodata.json or dump the database?

### mamba

- [] get fastest mirror automatically (librepo has a cool function for that)
- [] do not invalidate cache: need to write some "main" url into the repodata_record.json

**Comment by wolfv** [comment]
I marked the mirroring without reindexing one as done, correct @btel?
