### ISSUE TITLE
improve jobs framework

### ISSUE THREAD

**Issue by btel** [mamba-org/quetz#282]
there are a few issues in jobs framework:

- [x] all jobs are immediately in "running" state (even though they are waiting to be executed (maybe introduce another state?),  #285 
- [x] when killing the watcher process, cannot resume (because there is some jobid stored somewhere that cannot be found in the dict anymore),  #287
- [x]  store which jobs have already been executed, so transmuting does not re-run on previously transmuted packages again, #291

**Comment by btel** [comment]
@wolfv I am done with the list of issues, anything to add?

**Comment by btel** [comment]
one thing, which we might implement is adding an option to force a rerun of jobs on all packages

**Comment by wolfv** [comment]
yes, force-rerun would be good to have.
